/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminAkunRouteImport } from './routes/_app/admin/akun'
import { Route as AppAdminIzinRouteImport } from './routes/_app/admin/izin'
import { Route as AppAdminMasterRouteImport } from './routes/_app/admin/master'
import { Route as AppAdminRekapRouteImport } from './routes/_app/admin/rekap'
import { Route as AppGuruIndexRouteImport } from './routes/_app/guru/index'
import { Route as AppGuruIzinRouteImport } from './routes/_app/guru/izin'
import { Route as AppGuruMuridRouteImport } from './routes/_app/guru/murid'
import { Route as AppWaliIndexRouteImport } from './routes/_app/wali/index'
import { Route as AppWaliIzinRouteImport } from './routes/_app/wali/izin'
import { Route as AppWaliMuridRouteImport } from './routes/_app/wali/murid'
import { Route as AppWaliRekapRouteImport } from './routes/_app/wali/rekap'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAkunRoute = AppAdminAkunRouteImport.update({
  id: '/admin/akun',
  path: '/admin/akun',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIzinRoute = AppAdminIzinRouteImport.update({
  id: '/admin/izin',
  path: '/admin/izin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMasterRoute = AppAdminMasterRouteImport.update({
  id: '/admin/master',
  path: '/admin/master',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRekapRoute = AppAdminRekapRouteImport.update({
  id: '/admin/rekap',
  path: '/admin/rekap',
  getParentRoute: () => AppRoute,
} as any)
const AppGuruIndexRoute = AppGuruIndexRouteImport.update({
  id: '/guru/',
  path: '/guru/',
  getParentRoute: () => AppRoute,
} as any)
const AppGuruIzinRoute = AppGuruIzinRouteImport.update({
  id: '/guru/izin',
  path: '/guru/izin',
  getParentRoute: () => AppRoute,
} as any)
const AppGuruMuridRoute = AppGuruMuridRouteImport.update({
  id: '/guru/murid',
  path: '/guru/murid',
  getParentRoute: () => AppRoute,
} as any)
const AppWaliIndexRoute = AppWaliIndexRouteImport.update({
  id: '/wali/',
  path: '/wali/',
  getParentRoute: () => AppRoute,
} as any)
const AppWaliIzinRoute = AppWaliIzinRouteImport.update({
  id: '/wali/izin',
  path: '/wali/izin',
  getParentRoute: () => AppRoute,
} as any)
const AppWaliMuridRoute = AppWaliMuridRouteImport.update({
  id: '/wali/murid',
  path: '/wali/murid',
  getParentRoute: () => AppRoute,
} as any)
const AppWaliRekapRoute = AppWaliRekapRouteImport.update({
  id: '/wali/rekap',
  path: '/wali/rekap',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/akun': typeof AppAdminAkunRoute
  '/admin/izin': typeof AppAdminIzinRoute
  '/admin/master': typeof AppAdminMasterRoute
  '/admin/rekap': typeof AppAdminRekapRoute
  '/guru/izin': typeof AppGuruIzinRoute
  '/guru/murid': typeof AppGuruMuridRoute
  '/wali/izin': typeof AppWaliIzinRoute
  '/wali/murid': typeof AppWaliMuridRoute
  '/wali/rekap': typeof AppWaliRekapRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/guru/': typeof AppGuruIndexRoute
  '/wali/': typeof AppWaliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/akun': typeof AppAdminAkunRoute
  '/admin/izin': typeof AppAdminIzinRoute
  '/admin/master': typeof AppAdminMasterRoute
  '/admin/rekap': typeof AppAdminRekapRoute
  '/guru/izin': typeof AppGuruIzinRoute
  '/guru/murid': typeof AppGuruMuridRoute
  '/wali/izin': typeof AppWaliIzinRoute
  '/wali/murid': typeof AppWaliMuridRoute
  '/wali/rekap': typeof AppWaliRekapRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/guru': typeof AppGuruIndexRoute
  '/wali': typeof AppWaliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin/akun': typeof AppAdminAkunRoute
  '/_app/admin/izin': typeof AppAdminIzinRoute
  '/_app/admin/master': typeof AppAdminMasterRoute
  '/_app/admin/rekap': typeof AppAdminRekapRoute
  '/_app/guru/izin': typeof AppGuruIzinRoute
  '/_app/guru/murid': typeof AppGuruMuridRoute
  '/_app/wali/izin': typeof AppWaliIzinRoute
  '/_app/wali/murid': typeof AppWaliMuridRoute
  '/_app/wali/rekap': typeof AppWaliRekapRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/guru/': typeof AppGuruIndexRoute
  '/_app/wali/': typeof AppWaliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/akun'
    | '/admin/izin'
    | '/admin/master'
    | '/admin/rekap'
    | '/guru/izin'
    | '/guru/murid'
    | '/wali/izin'
    | '/wali/murid'
    | '/wali/rekap'
    | '/api/auth/$'
    | '/admin/'
    | '/guru/'
    | '/wali/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/akun'
    | '/admin/izin'
    | '/admin/master'
    | '/admin/rekap'
    | '/guru/izin'
    | '/guru/murid'
    | '/wali/izin'
    | '/wali/murid'
    | '/wali/rekap'
    | '/api/auth/$'
    | '/admin'
    | '/guru'
    | '/wali'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin/akun'
    | '/_app/admin/izin'
    | '/_app/admin/master'
    | '/_app/admin/rekap'
    | '/_app/guru/izin'
    | '/_app/guru/murid'
    | '/_app/wali/izin'
    | '/_app/wali/murid'
    | '/_app/wali/rekap'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_app/guru/'
    | '/_app/wali/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/akun': {
      id: '/_app/admin/akun'
      path: '/admin/akun'
      fullPath: '/admin/akun'
      preLoaderRoute: typeof AppAdminAkunRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/izin': {
      id: '/_app/admin/izin'
      path: '/admin/izin'
      fullPath: '/admin/izin'
      preLoaderRoute: typeof AppAdminIzinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/master': {
      id: '/_app/admin/master'
      path: '/admin/master'
      fullPath: '/admin/master'
      preLoaderRoute: typeof AppAdminMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/rekap': {
      id: '/_app/admin/rekap'
      path: '/admin/rekap'
      fullPath: '/admin/rekap'
      preLoaderRoute: typeof AppAdminRekapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guru/': {
      id: '/_app/guru/'
      path: '/guru'
      fullPath: '/guru/'
      preLoaderRoute: typeof AppGuruIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guru/izin': {
      id: '/_app/guru/izin'
      path: '/guru/izin'
      fullPath: '/guru/izin'
      preLoaderRoute: typeof AppGuruIzinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guru/murid': {
      id: '/_app/guru/murid'
      path: '/guru/murid'
      fullPath: '/guru/murid'
      preLoaderRoute: typeof AppGuruMuridRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wali/': {
      id: '/_app/wali/'
      path: '/wali'
      fullPath: '/wali/'
      preLoaderRoute: typeof AppWaliIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wali/izin': {
      id: '/_app/wali/izin'
      path: '/wali/izin'
      fullPath: '/wali/izin'
      preLoaderRoute: typeof AppWaliIzinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wali/murid': {
      id: '/_app/wali/murid'
      path: '/wali/murid'
      fullPath: '/wali/murid'
      preLoaderRoute: typeof AppWaliMuridRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wali/rekap': {
      id: '/_app/wali/rekap'
      path: '/wali/rekap'
      fullPath: '/wali/rekap'
      preLoaderRoute: typeof AppWaliRekapRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminAkunRoute: typeof AppAdminAkunRoute
  AppAdminIzinRoute: typeof AppAdminIzinRoute
  AppAdminMasterRoute: typeof AppAdminMasterRoute
  AppAdminRekapRoute: typeof AppAdminRekapRoute
  AppGuruIzinRoute: typeof AppGuruIzinRoute
  AppGuruMuridRoute: typeof AppGuruMuridRoute
  AppWaliIzinRoute: typeof AppWaliIzinRoute
  AppWaliMuridRoute: typeof AppWaliMuridRoute
  AppWaliRekapRoute: typeof AppWaliRekapRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppGuruIndexRoute: typeof AppGuruIndexRoute
  AppWaliIndexRoute: typeof AppWaliIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminAkunRoute: AppAdminAkunRoute,
  AppAdminIzinRoute: AppAdminIzinRoute,
  AppAdminMasterRoute: AppAdminMasterRoute,
  AppAdminRekapRoute: AppAdminRekapRoute,
  AppGuruIzinRoute: AppGuruIzinRoute,
  AppGuruMuridRoute: AppGuruMuridRoute,
  AppWaliIzinRoute: AppWaliIzinRoute,
  AppWaliMuridRoute: AppWaliMuridRoute,
  AppWaliRekapRoute: AppWaliRekapRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppGuruIndexRoute: AppGuruIndexRoute,
  AppWaliIndexRoute: AppWaliIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
